# Generated by Django 5.2.4 on 2025-07-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='vehicle_make',
            field=models.CharField(blank=True, help_text='Vehicle manufacturer (e.g., Toyota, Ford, Honda)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='Vehicle model (e.g., Camry, F-150, Civic)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_year',
            field=models.IntegerField(blank=True, help_text='Year of the vehicle (e.g., 2020)', null=True),
        ),
    ]
