# Generated by Django 5.2.4 on 2025-07-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_vehicle_make_lead_vehicle_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='zip_code',
            field=models.CharField(default=0, help_text='ZIP code (e.g., 12345 or 12345-6789)', max_length=10),
            preserve_default=False,
        ),
    ]
