# Generated by Django 5.2.4 on 2025-07-29 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='zip_code',
            field=models.CharField(help_text='ZIP code (e.g., 12345 or 12345-6789)', max_length=10, validators=[django.core.validators.RegexValidator(message='ZIP code must be in format: 12345 or 12345-6789', regex='^\\d{5}(-\\d{4})?$')]),
        ),
    ]
