# Generated by Django 5.2.4 on 2025-07-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_add_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='vehicle_year',
        ),
        migrations.AddField(
            model_name='lead',
            name='accidents_past_year',
            field=models.IntegerField(default=0, help_text='Number of accidents in the past year'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_homeowner',
            field=models.BooleanField(default=False, help_text='Is the lead a homeowner?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tickets_past_year',
            field=models.IntegerField(default=0, help_text='Number of traffic tickets received in the past year'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(help_text='Select a state', max_length=2),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year of the vehicle (e.g., 2020)')),
                ('make', models.CharField(help_text='Vehicle manufacturer (e.g., Toyota, Ford, Honda)', max_length=50)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Camry, F-150, Civic)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(help_text='The lead who owns this vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
