# Generated by Django 5.2.4 on 2025-07-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the subscriber who receives leads', max_length=254, unique=True)),
                ('number_of_leads_purchased', models.PositiveIntegerField(default=0, help_text='Total number of leads purchased by this subscriber')),
                ('number_of_leads_sent', models.PositiveIntegerField(default=0, help_text='Total number of leads sent to this subscriber')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leads Subscriber',
                'verbose_name_plural': 'Leads Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(help_text='Select a state', max_length=2),
        ),
    ]
