# Generated by Django 5.2.4 on 2025-07-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadssubscriber_alter_lead_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadssubscriber',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the subscriber currently active?'),
        ),
    ]
