version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=1
      - DATABASE_URL=sqlite:///db.sqlite3
      - ALLOWED_HOSTS=savedrivenow.siber.live,
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=savedrivenow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "8642:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
